# Generated by Django 5.1.4 on 2024-12-20 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agulha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Numero da agulha')),
            ],
            options={
                'verbose_name': 'Agulha',
                'verbose_name_plural': 'Agulhas',
            },
        ),
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Cor',
                'verbose_name_plural': 'Cores',
            },
        ),
        migrations.CreateModel(
            name='Enchimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='quantidade')),
            ],
            options={
                'verbose_name': 'Enchimento',
                'verbose_name_plural': 'Enchimentos',
            },
        ),
        migrations.CreateModel(
            name='Marca_linha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Marca_linha',
                'verbose_name_plural': 'Marca_linhas',
            },
        ),
        migrations.CreateModel(
            name='Tipo_agulha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo_agulha',
                'verbose_name_plural': 'Tipo_agulhas',
            },
        ),
        migrations.CreateModel(
            name='Tipo_enchimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo_enchimento',
                'verbose_name_plural': 'Tipo_enchimentos',
            },
        ),
        migrations.CreateModel(
            name='Tipo_linha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo_linha',
                'verbose_name_plural': 'Tipo_linhas',
            },
        ),
        migrations.CreateModel(
            name='Linha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.IntegerField(verbose_name='Tamanho')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('Cor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cor', verbose_name='Cor')),
                ('Marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.marca_linha', verbose_name='Marca')),
                ('Tipo_linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipo_linha', verbose_name='Tipo_linha')),
            ],
            options={
                'verbose_name': 'Linha',
                'verbose_name_plural': 'Linhas',
            },
        ),
        migrations.CreateModel(
            name='Materiais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agulha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.agulha', verbose_name='Agulha')),
                ('enchimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.enchimento', verbose_name='Enchimento')),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.linha', verbose_name='Linha')),
            ],
            options={
                'verbose_name': 'Materiais',
                'verbose_name_plural': 'Materiais',
            },
        ),
        migrations.AddField(
            model_name='agulha',
            name='Tipo_agulha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipo_agulha', verbose_name='Tipo_agulha'),
        ),
        migrations.AddField(
            model_name='enchimento',
            name='Tipo_enchimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipo_enchimento', verbose_name='Tipo_enchimento'),
        ),
    ]
