# Generated by Django 5.1.4 on 2024-12-20 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materiais',
            options={'verbose_name': 'Materiais', 'verbose_name_plural': 'Materiaiss'},
        ),
        migrations.RenameField(
            model_name='agulha',
            old_name='Tipo_agulha',
            new_name='tipo_agulha',
        ),
        migrations.RenameField(
            model_name='enchimento',
            old_name='Tipo_enchimento',
            new_name='tipo_enchimento',
        ),
        migrations.RenameField(
            model_name='linha',
            old_name='Cor',
            new_name='cor',
        ),
        migrations.RenameField(
            model_name='linha',
            old_name='Marca',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='linha',
            old_name='Tipo_linha',
            new_name='tipo_linha',
        ),
        migrations.AlterField(
            model_name='materiais',
            name='agulha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais_relacionados', to='app.agulha', verbose_name='Agulha'),
        ),
    ]
