# Generated by Django 5.1.4 on 2024-12-20 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_materiais_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agulha',
            name='materiais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agulhas_relacionadas', to='app.materiais', verbose_name='Materiais'),
            preserve_default=False,
        ),
    ]
