# Generated by Django 5.1.4 on 2025-01-14 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_agulha_materiais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materiais',
            options={'verbose_name': 'Materiais', 'verbose_name_plural': 'Materiais'},
        ),
    ]
