# Generated by Django 5.1.5 on 2025-02-03 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_categoria_receita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agulha',
            name='materiais',
        ),
    ]
